### ISSUE TITLE
transportation-on-vacation.js

### ISSUE THREAD

**Issue by sninala** [divyagandivalasa/javascript-training#1]
1. The line totalCarRent = numberOfDays * 40; is duplicated in the conditions..
2. you can even simplify the logic also as below
totalCarRent = numberOfDays * 40;
    if (numberOfDays  >= 7) {
        totalCarRent -= 50;
    } else if (numberOfDays  >= 3 && numberOfDays  < 7) {
        totalCarRent -= 20;
    }

**Comment by divyagandivalasa** [comment]
Worked on the duplicate code and pushed it to the repository.

**Comment by sninala** [comment]
looks good now.
